language: node_js

node_js:
   - "0.8"
   - "0.9"
   - "0.10"
   - "0.11"
   - "0.12"
   - "iojs-v1.6"
   - "iojs-v2"
   - "iojs-v3"
   - "4.0"

services:
   - rabbitmq

before_install:
  - npm install -g npm@2

sudo: false
